# Generated by Django 5.2.5 on 2025-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0002_user_date_of_birth_user_designation_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
