# Generated by Django 5.2.5 on 2025-09-09 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0005_pinpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesession',
            options={},
        ),
        migrations.RenameField(
            model_name='livesession',
            old_name='ended_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='livesession',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='livesession',
            old_name='started_at',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='pinpoint',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='pinpoint',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='pinpoint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pinpoint',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinpoints', to='attendenceapp.livesession'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pinpoint',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeLocation',
        ),
    ]
