# Generated by Django 5.2.5 on 2025-09-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0008_livesession_current_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserScreedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('services', models.JSONField()),
                ('need_troweling', models.CharField(blank=True, max_length=10, null=True)),
                ('troweling_color', models.CharField(blank=True, max_length=20, null=True)),
                ('sqft_range', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
